import mongodb from "mongodb";

const command = process.argv[2];
try {
  if (command === "quickseed") {
    quickseed();
  } else if (command === "quickgone") {
    quickgone();
  }
} catch (error) {
  console.error("Error occurred:", error);
}

async function quickseed() {
  const client = new mongodb.MongoClient("mongodb://localhost:27017");
  await client.connect();
  const myDB = client.db("Stations");
  const myColl = myDB.collection("zStations");
const myDoc = [
{ name: "Z Vivian St", address: "174 Vivian St, Te Aro, Wellington", latitude: -41.2946, longitude: 174.7756, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.89, ZX_Premium: 3.09, Z_Diesel: 2.29 }, real: true },
{ name: "Z Whitmore St", address: "1 Whitmore St, Wellington Central, Wellington", latitude: -41.2816, longitude: 174.7788, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.91, ZX_Premium: 3.11, Z_Diesel: 2.31 }, real: true },
{ name: "Z Broadway", address: "Cnr Calabar Rd & Broadway, Miramar, Wellington", latitude: -41.3220, longitude: 174.8064, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: true },
{ name: "Z Constable St", address: "35 Constable St, Newtown, Wellington", latitude: -41.3129, longitude: 174.7797, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.87, ZX_Premium: 3.07, Z_Diesel: 2.27 }, real: true },
{ name: "Z Kilbirnie", address: "16-22 Coutts St, Kilbirnie, Wellington", latitude: -41.3251, longitude: 174.7965, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: true },
{ name: "Z Mana", address: "143 Mana Esplanade, Mana, Wellington", latitude: -41.1067, longitude: 174.8654, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: true },
{ name: "Z Orakei", address: "154 Kepa Rd, Orakei, Auckland", latitude: -36.8583, longitude: 174.8177, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.92, ZX_Premium: 3.12, Z_Diesel: 2.32 }, real: true },
{ name: "Z Takapuna", address: "Cnr Northcote Rd & Taharoto Rd, Takapuna, Auckland", latitude: -36.7891, longitude: 174.7614, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.90, ZX_Premium: 3.10, Z_Diesel: 2.30 }, real: true },
{ name: "Z Manurewa", address: "1 Alfriston Rd, Manurewa, South Auckland", latitude: -37.0086, longitude: 174.8991, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.81, ZX_Premium: 3.01, Z_Diesel: 2.21 }, real: true },
{ name: "Z Henderson", address: "198 Lincoln Rd, Henderson, Auckland", latitude: -36.8742, longitude: 174.6284, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.84, ZX_Premium: 3.04, Z_Diesel: 2.24 }, real: true },
{ name: "Z Papakura", address: "26 Clevedon Rd, Papakura", latitude: -37.0637, longitude: 174.9453, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.80, ZX_Premium: 3.00, Z_Diesel: 2.20 }, real: true },
{ name: "Z Manukau", address: "742 Great South Rd, Manukau City", latitude: -36.9928, longitude: 174.8797, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.82, ZX_Premium: 3.02, Z_Diesel: 2.22 }, real: true },
{ name: "Z Kumeu", address: "134-152 Main Rd, SH16, Kumeu, Auckland", latitude: -36.7936, longitude: 174.5511, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.78, ZX_Premium: 2.98, Z_Diesel: 2.18 }, real: true },
{ name: "Z Karaka", address: "47 Harbourside Dr, Karaka, Auckland", latitude: -37.0842, longitude: 174.8235, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "AdBlue Diesel Exhaust Fluid"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.76, ZX_Premium: 2.96, Z_Diesel: 2.16 }, real: true },
{ name: "Z Wiri", address: "83 Wiri Station Rd, Manukau", latitude: -37.0089, longitude: 174.8592, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "LPG SWAP'n'GO"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.77, ZX_Premium: 2.97, Z_Diesel: 2.17 }, real: true },
{ name: "Z Woolston", address: "417 Ferry Rd, Woolston, Christchurch", latitude: -43.5486, longitude: 172.6733, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.75, ZX_Premium: 2.95, Z_Diesel: 2.15 }, real: true },
{ name: "Z Linwood", address: "Cnr Linwood Ave & Cashel St, Christchurch", latitude: -43.5346, longitude: 172.6664, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.74, ZX_Premium: 2.94, Z_Diesel: 2.14 }, real: true },
{ name: "Z Christchurch North", address: "1413 Main North Rd, Christchurch", latitude: -43.4557, longitude: 172.6142, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.73, ZX_Premium: 2.93, Z_Diesel: 2.13 }, real: true },
{ name: "Z Napier South", address: "Cnr Tennyson St & Station St, Napier South", latitude: -39.4928, longitude: 176.9120, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.79, ZX_Premium: 2.99, Z_Diesel: 2.19 }, real: true },
{ name: "Z Whangarei", address: "Cnr Kamo Rd & Nixon St, Kensington, Whangarei", latitude: -35.7175, longitude: 174.3327, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.88, ZX_Premium: 3.08, Z_Diesel: 2.28 }, real: true },
{ name: "Z Levin", address: "State Highway 1, Levin", latitude: -40.6229, longitude: 175.2856, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "24/7 Pay at Pump"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.72, ZX_Premium: 2.92, Z_Diesel: 2.12 }, real: true },
{ name: "Z Marton", address: "166 Broadway, Marton", latitude: -40.0631, longitude: 175.3667, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.71, ZX_Premium: 2.91, Z_Diesel: 2.11 }, real: true },
{ name: "Z Masterton", address: "State Highway 2, Masterton", latitude: -40.9511, longitude: 175.6572, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: true },
{ name: "Z Matamata", address: "Cnr Waharoa Rd & Peria Rd, Matamata", latitude: -37.8062, longitude: 175.7654, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.80, ZX_Premium: 3.00, Z_Diesel: 2.20 }, real: true },
{ name: "Z Hastings", address: "Parkvale, Hastings", latitude: -39.6413, longitude: 176.8508, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: true },
{ name: "Z Rotorua Central", address: "142 Fenton St, Rotorua", latitude: -38.1446, longitude: 176.2510, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: false },
{ name: "Z Taupo Lakefront", address: "88 Lake Terrace, Taupo", latitude: -38.6857, longitude: 176.0702, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Z Express Coffee & Fresh Food"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 2, total: 2 }, { type: "CHAdeMO", max_kw: 50, available: 1, total: 2 }], prices: { Z91_Unleaded: 2.84, ZX_Premium: 3.04, Z_Diesel: 2.24, EV_Charging: 0.89 }, real: false },
{ name: "Z Hamilton East", address: "210 Grey St, Hamilton East, Hamilton", latitude: -37.7899, longitude: 175.2998, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.81, ZX_Premium: 3.01, Z_Diesel: 2.21 }, real: false },
{ name: "Z Hamilton West", address: "55 Whatawhata Rd, Hamilton", latitude: -37.7826, longitude: 175.2400, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.77, ZX_Premium: 2.97, Z_Diesel: 2.17 }, real: false },
{ name: "Z Tauranga Central", address: "300 Cameron Rd, Tauranga", latitude: -37.6931, longitude: 176.1653, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 120, available: 1, total: 2 }, { type: "CHAdeMO", max_kw: 50, available: 2, total: 2 }], prices: { Z91_Unleaded: 2.89, ZX_Premium: 3.09, Z_Diesel: 2.29, EV_Charging: 0.92 }, real: false },
{ name: "Z Mount Maunganui", address: "12 Maunganui Rd, Mount Maunganui", latitude: -37.6337, longitude: 176.1836, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.90, ZX_Premium: 3.10, Z_Diesel: 2.30 }, real: false },
{ name: "Z New Plymouth", address: "77 Devon St East, New Plymouth", latitude: -39.0578, longitude: 174.0798, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.79, ZX_Premium: 2.99, Z_Diesel: 2.19 }, real: false },
{ name: "Z Palmerston North", address: "410 Main St, Palmerston North", latitude: -40.3567, longitude: 175.6086, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.82, ZX_Premium: 3.02, Z_Diesel: 2.22 }, real: false },
{ name: "Z Wanganui", address: "150 Victoria Ave, Whanganui", latitude: -39.9301, longitude: 175.0470, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.78, ZX_Premium: 2.98, Z_Diesel: 2.18 }, real: false },
{ name: "Z Nelson City", address: "95 Trafalgar St, Nelson", latitude: -41.2706, longitude: 173.2840, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "ATM", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 1 }, { type: "CHAdeMO", max_kw: 120, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25, EV_Charging: 0.94 }, real: false },
{ name: "Z Blenheim", address: "60 Queen St, Blenheim", latitude: -41.5134, longitude: 173.9612, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: false },
{ name: "Z Dunedin Central", address: "220 George St, Dunedin", latitude: -45.8742, longitude: 170.5036, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.87, ZX_Premium: 3.07, Z_Diesel: 2.27 }, real: false },
{ name: "Z Dunedin South", address: "45 Andersons Bay Rd, Dunedin", latitude: -45.8890, longitude: 170.5127, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "AdBlue Diesel Exhaust Fluid"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.75, ZX_Premium: 2.95, Z_Diesel: 2.15 }, real: false },
{ name: "Z Invercargill", address: "88 Dee St, Invercargill", latitude: -46.4132, longitude: 168.3538, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.80, ZX_Premium: 3.00, Z_Diesel: 2.20 }, real: false },
{ name: "Z Queenstown", address: "10 Gorge Rd, Queenstown", latitude: -45.0312, longitude: 168.6626, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 120, available: 2, total: 3 }, { type: "CHAdeMO", max_kw: 50, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.95, ZX_Premium: 3.15, Z_Diesel: 2.35, EV_Charging: 0.98 }, real: false },
{ name: "Z Wanaka", address: "22 Ardmore St, Wanaka", latitude: -44.7032, longitude: 169.1321, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.93, ZX_Premium: 3.13, Z_Diesel: 2.33 }, real: false },
{ name: "Z Timaru", address: "150 Stafford St, Timaru", latitude: -44.3971, longitude: 171.2543, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.81, ZX_Premium: 3.01, Z_Diesel: 2.21 }, real: false },
{ name: "Z Ashburton", address: "300 East St, Ashburton", latitude: -43.9047, longitude: 171.7495, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "LPG SWAP'n'GO"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.76, ZX_Premium: 2.96, Z_Diesel: 2.16 }, real: false },
{ name: "Z Rangiora", address: "180 High St, Rangiora", latitude: -43.3042, longitude: 172.5966, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.79, ZX_Premium: 2.99, Z_Diesel: 2.19 }, real: false },
{ name: "Z Gisborne", address: "50 Gladstone Rd, Gisborne", latitude: -38.6624, longitude: 178.0176, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.91, ZX_Premium: 3.11, Z_Diesel: 2.31 }, real: false },
{ name: "Z Rotorua North", address: "500 Old Taupo Rd, Rotorua", latitude: -38.1195, longitude: 176.2620, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "24/7 Pay at Pump"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.74, ZX_Premium: 2.94, Z_Diesel: 2.14 }, real: false },
{ name: "Z Cambridge", address: "88 Victoria St, Cambridge", latitude: -37.8874, longitude: 175.4692, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.82, ZX_Premium: 3.02, Z_Diesel: 2.22 }, real: false },
{ name: "Z Te Awamutu", address: "120 Alexandra St, Te Awamutu", latitude: -38.0088, longitude: 175.3230, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.80, ZX_Premium: 3.00, Z_Diesel: 2.20 }, real: false },
{ name: "Z Porirua", address: "45 Titahi Bay Rd, Porirua, Wellington", latitude: -41.1394, longitude: 174.8407, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: false },
{ name: "Z Upper Hutt", address: "200 Main St, Upper Hutt, Wellington", latitude: -41.1228, longitude: 175.0508, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 2 }, { type: "CHAdeMO", max_kw: 50, available: 2, total: 2 }], prices: { Z91_Unleaded: 2.84, ZX_Premium: 3.04, Z_Diesel: 2.24, EV_Charging: 0.90 }, real: false },
{ name: "Z Thorndon", address: "45 Thorndon Quay, Thorndon, Wellington", latitude: -41.2724, longitude: 174.7776, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.90, ZX_Premium: 3.10, Z_Diesel: 2.30 }, real: false },
{ name: "Z Karori", address: "210 Karori Rd, Karori, Wellington", latitude: -41.2896, longitude: 174.7332, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.88, ZX_Premium: 3.08, Z_Diesel: 2.28 }, real: false },
{ name: "Z Lower Hutt", address: "180 High St, Lower Hutt", latitude: -41.2127, longitude: 174.8977, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.87, ZX_Premium: 3.07, Z_Diesel: 2.27 }, real: false },
{ name: "Z Petone", address: "20 Jackson St, Petone, Lower Hutt", latitude: -41.2242, longitude: 174.8724, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: false },
{ name: "Z Newtown", address: "220 Riddiford St, Newtown, Wellington", latitude: -41.3130, longitude: 174.7793, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Z Express Coffee & Fresh Food"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26, EV_Charging: 0.91 }, real: false },
{ name: "Z Ponsonby", address: "180 Ponsonby Rd, Ponsonby, Auckland", latitude: -36.8556, longitude: 174.7444, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.93, ZX_Premium: 3.13, Z_Diesel: 2.33 }, real: false },
{ name: "Z Mount Eden", address: "400 Mount Eden Rd, Mount Eden, Auckland", latitude: -36.8783, longitude: 174.7621, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.91, ZX_Premium: 3.11, Z_Diesel: 2.31 }, real: false },
{ name: "Z Newmarket", address: "277 Broadway, Newmarket, Auckland", latitude: -36.8709, longitude: 174.7770, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 120, available: 2, total: 2 }], prices: { Z91_Unleaded: 2.94, ZX_Premium: 3.14, Z_Diesel: 2.34, EV_Charging: 0.95 }, real: false },
{ name: "Z Onehunga", address: "150 Onehunga Mall, Onehunga, Auckland", latitude: -36.9163, longitude: 174.7818, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: false },
{ name: "Z Panmure", address: "10 Lagoon Dr, Panmure, Auckland", latitude: -36.8944, longitude: 174.8497, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.79, ZX_Premium: 2.99, Z_Diesel: 2.19 }, real: false },
{ name: "Z Botany", address: "588 Chapel Rd, Botany Downs, Auckland", latitude: -36.9280, longitude: 174.9110, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: false },
{ name: "Z Albany", address: "219 Don McKinnon Dr, Albany, Auckland", latitude: -36.7307, longitude: 174.7000, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.89, ZX_Premium: 3.09, Z_Diesel: 2.29 }, real: false },
{ name: "Z Glenfield", address: "477 Glenfield Rd, Glenfield, Auckland", latitude: -36.7833, longitude: 174.7222, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.88, ZX_Premium: 3.08, Z_Diesel: 2.28 }, real: false },
{ name: "Z Riccarton", address: "129 Riccarton Rd, Riccarton, Christchurch", latitude: -43.5297, longitude: 172.5987, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.76, ZX_Premium: 2.96, Z_Diesel: 2.16 }, real: false },
{ name: "Z Papanui", address: "260 Papanui Rd, Papanui, Christchurch", latitude: -43.5024, longitude: 172.6180, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.75, ZX_Premium: 2.95, Z_Diesel: 2.15 }, real: false },
{ name: "Z Hornby", address: "477 Main South Rd, Hornby, Christchurch", latitude: -43.5477, longitude: 172.5359, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "AdBlue Diesel Exhaust Fluid"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.73, ZX_Premium: 2.93, Z_Diesel: 2.13 }, real: false },
{ name: "Z New Brighton", address: "128 Marine Parade, New Brighton, Christchurch", latitude: -43.5065, longitude: 172.7290, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "ATM", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.74, ZX_Premium: 2.94, Z_Diesel: 2.14, EV_Charging: 0.88 }, real: false },
{ name: "Z Hillcrest", address: "300 Ruakura Rd, Hillcrest, Hamilton", latitude: -37.7900, longitude: 175.3229, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: false },
{ name: "Z Chartwell", address: "Corner Te Rapa Rd, Chartwell, Hamilton", latitude: -37.7628, longitude: 175.2621, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "LPG SWAP'n'GO"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.78, ZX_Premium: 2.98, Z_Diesel: 2.18 }, real: false },
{ name: "Z Otumoetai", address: "150 Otumoetai Rd, Otumoetai, Tauranga", latitude: -37.6714, longitude: 176.1361, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.88, ZX_Premium: 3.08, Z_Diesel: 2.28 }, real: false },
{ name: "Z Papamoa", address: "20 Gravatt Rd, Papamoa, Tauranga", latitude: -37.6903, longitude: 176.2712, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.90, ZX_Premium: 3.10, Z_Diesel: 2.30 }, real: false },
{ name: "Z Rotorua Fenton South", address: "800 Fenton St, Rotorua", latitude: -38.1560, longitude: 176.2489, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.87, ZX_Premium: 3.07, Z_Diesel: 2.27 }, real: false },
{ name: "Z Taupo East", address: "50 Spa Rd, Taupo", latitude: -38.6825, longitude: 176.0925, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "24/7 Pay at Pump"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: false },
{ name: "Z Fitzroy", address: "150 Devon St West, Fitzroy, New Plymouth", latitude: -39.0500, longitude: 174.0917, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.81, ZX_Premium: 3.01, Z_Diesel: 2.21 }, real: false },
{ name: "Z Westown", address: "300 Devon St East, Westown, New Plymouth", latitude: -39.0625, longitude: 174.0631, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.77, ZX_Premium: 2.97, Z_Diesel: 2.17 }, real: false },
{ name: "Z Terrace End", address: "150 Rangitikei St, Palmerston North", latitude: -40.3467, longitude: 175.6117, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.80, ZX_Premium: 3.00, Z_Diesel: 2.20 }, real: false },
{ name: "Z Kelvin Grove", address: "220 Botanical Rd, Palmerston North", latitude: -40.3708, longitude: 175.6019, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.84, ZX_Premium: 3.04, Z_Diesel: 2.24, EV_Charging: 0.90 }, real: false },
{ name: "Z Motueka", address: "200 High St, Motueka", latitude: -41.1150, longitude: 173.0000, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: false },
{ name: "Z Stoke", address: "300 Main Rd, Stoke, Nelson", latitude: -41.3006, longitude: 173.2825, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "AdBlue Diesel Exhaust Fluid"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: false },
{ name: "Z Mosgiel", address: "150 Gordon Rd, Mosgiel, Dunedin", latitude: -45.8804, longitude: 170.3600, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: false },
{ name: "Z North Dunedin", address: "300 North Rd, North Dunedin", latitude: -45.8564, longitude: 170.5142, station_type: "Service Station", open24Hours: true, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.88, ZX_Premium: 3.08, Z_Diesel: 2.28 }, real: false },
{ name: "Z Frankton", address: "20 Athol St, Frankton, Queenstown", latitude: -45.0392, longitude: 168.7411, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.96, ZX_Premium: 3.16, Z_Diesel: 2.36 }, real: false },
{ name: "Z Cromwell", address: "50 Melmore Terrace, Cromwell", latitude: -45.0392, longitude: 169.1997, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "LPG SWAP'n'GO"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.92, ZX_Premium: 3.12, Z_Diesel: 2.32 }, real: false },
{ name: "Z Geraldine", address: "50 Talbot St, Geraldine", latitude: -44.0942, longitude: 171.2419, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.82, ZX_Premium: 3.02, Z_Diesel: 2.22 }, real: false },
{ name: "Z Waimate", address: "100 Queen St, Waimate", latitude: -44.7333, longitude: 171.0500, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.83, ZX_Premium: 3.03, Z_Diesel: 2.23 }, real: false },
{ name: "Z Feilding", address: "20 Kimbolton Rd, Feilding", latitude: -40.2278, longitude: 175.5644, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.79, ZX_Premium: 2.99, Z_Diesel: 2.19 }, real: false },
{ name: "Z Waipukurau", address: "50 Ruataniwha St, Waipukurau", latitude: -40.0028, longitude: 176.5606, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "24/7 Pay at Pump"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.81, ZX_Premium: 3.01, Z_Diesel: 2.21 }, real: false },
{ name: "Z Kaitaia", address: "50 Commerce St, Kaitaia", latitude: -35.1136, longitude: 173.2631, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z20 carwash", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.94, ZX_Premium: 3.14, Z_Diesel: 2.34 }, real: false },
{ name: "Z Kerikeri", address: "20 Kerikeri Rd, Kerikeri", latitude: -35.2269, longitude: 173.9500, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.92, ZX_Premium: 3.12, Z_Diesel: 2.32 }, real: false },
{ name: "Z Dargaville", address: "80 Victoria St, Dargaville", latitude: -35.9350, longitude: 173.8781, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.90, ZX_Premium: 3.10, Z_Diesel: 2.30 }, real: false },
{ name: "Z Gisborne East", address: "150 Wainui Rd, Gisborne", latitude: -38.6600, longitude: 178.0350, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.93, ZX_Premium: 3.13, Z_Diesel: 2.33 }, real: false },
{ name: "Z Ruatoria", address: "40 Waiomatatini Rd, Ruatoria", latitude: -37.8894, longitude: 178.3186, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Compostable Cups"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.97, ZX_Premium: 3.17, Z_Diesel: 2.37 }, real: false },
{ name: "Z Wairoa", address: "100 Marine Parade, Wairoa", latitude: -39.0333, longitude: 177.4000, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "AdBlue Diesel Exhaust Fluid"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.91, ZX_Premium: 3.11, Z_Diesel: 2.31 }, real: false },
{ name: "Z Carterton", address: "150 High St, Carterton", latitude: -41.0225, longitude: 175.5300, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.84, ZX_Premium: 3.04, Z_Diesel: 2.24 }, real: false },
{ name: "Z Greytown", address: "50 Main St, Greytown", latitude: -41.0803, longitude: 175.4589, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee", "Club+"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.85, ZX_Premium: 3.05, Z_Diesel: 2.25 }, real: false },
{ name: "Z Greymouth", address: "20 Tainui St, Greymouth", latitude: -42.4500, longitude: 171.2100, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "LPG SWAP'n'GO"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.98, ZX_Premium: 3.18, Z_Diesel: 2.38 }, real: false },
{ name: "Z Westport", address: "150 Palmerston St, Westport", latitude: -41.7550, longitude: 171.6033, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "ATM", "Pay by plate"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.99, ZX_Premium: 3.19, Z_Diesel: 2.39 }, real: false },
{ name: "Z Hokitika", address: "80 Revell St, Hokitika", latitude: -42.7167, longitude: 170.9667, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "f'real", "24/7 Pay at Pump"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.97, ZX_Premium: 3.17, Z_Diesel: 2.37 }, real: false },
{ name: "Z Alexandra", address: "100 Centennial Ave, Alexandra", latitude: -45.2500, longitude: 169.3833, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "24/7 Pay at Pump"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.94, ZX_Premium: 3.14, Z_Diesel: 2.34 }, real: false },
{ name: "Z Balclutha", address: "50 Clyde St, Balclutha", latitude: -46.2333, longitude: 169.7500, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Z Express Coffee & Fresh Food", "ATM"], trailerHire: false, paymentMethods: ["Credit Card"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.89, ZX_Premium: 3.09, Z_Diesel: 2.29 }, real: false },
{ name: "Z Te Anau", address: "60 Milford Rd, Te Anau", latitude: -45.4167, longitude: 167.7167, station_type: "EV Charging", open24Hours: true, services: ["Restrooms", "Pay in app"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel", "EV Charging"], ev_chargers: [{ type: "CCS", max_kw: 50, available: 1, total: 1 }], prices: { Z91_Unleaded: 2.99, ZX_Premium: 3.19, Z_Diesel: 2.39, EV_Charging: 0.99 }, real: false },
{ name: "Z Oamaru", address: "150 Thames St, Oamaru", latitude: -45.0967, longitude: 170.9700, station_type: "Service Station", open24Hours: false, services: ["Restrooms", "Pre-order Coffee"], trailerHire: false, paymentMethods: ["Credit Card", "pay in app"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.86, ZX_Premium: 3.06, Z_Diesel: 2.26 }, real: false },
{ name: "Z Taumarunui", address: "80 Hakiaha St, Taumarunui", latitude: -38.8783, longitude: 175.2683, station_type: "Truck Stop", open24Hours: true, services: ["Restrooms", "Trailer hire", "Fast fill Diesel lane", "Super long hoses"], trailerHire: true, paymentMethods: ["Credit Card", "Pay at Pump"], fuelTypes: ["Z91", "Z95", "Diesel"], prices: { Z91_Unleaded: 2.87, ZX_Premium: 3.07, Z_Diesel: 2.27 }, real: false }
]
  await myColl.insertMany(myDoc);
  console.log("Documents inserted into zStations collection.");
  await client.close();
}

async function quickgone() {
  const client = new mongodb.MongoClient("mongodb://localhost:27017");
  await client.connect();
  const myDB = client.db("Stations");
  const myColl = myDB.collection("zStations");
  await myColl.deleteMany({});
  console.log("All documents deleted from zStations collection.");
  await client.close();
}
